desc "Corrige las zonas y perfiles nulos de telefonica"
task :corrige_usuarios => :environment do

  csv_users = [{ :mail => "claudia.gutierrez@telefonica.com", :role => "colaborador", :zone => "temm" },
	{ :mail => "darwin.fabian@telefonica.com", :role => "colaborador", :zone => "temm" },
	{ :mail => "delia.rojasv@telefonica.com", :role => "colaborador", :zone => "temm" },
	{ :mail => "ccomercial.mx@telefonica.com", :role => "colaborador", :zone => "temm" },
	{ :mail => "joser.hernandez.ext@telefonica.com", :role => "colaborador", :zone => "temm" },
	{ :mail => "julio.carrascoperez@telefonica.com", :role => "colaborador", :zone => "temm" },
	{ :mail => "luism.lopez@telefonica.com", :role => "colaborador", :zone => "temm" },
	{ :mail => "luis.arizmendi@telefonica.com", :role => "colaborador", :zone => "temm" },
	{ :mail => "melba.montante.ext@telefonica.com", :role => "colaborador", :zone => "temm" },
	{ :mail => "carlos.ramosru@telefonica.com", :role => "colaborador", :zone => "temm" },
	{ :mail => "aherman@humanforce.com.mx", :role => "distribuidor vip", :zone => "norte" },
	{ :mail => "albano@retpro.com.mx", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "ireyes@telefonica-mobile.com", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "mgalarza@tecnologiacelular.com.mx", :role => "distribuidor vip", :zone => "norte" },
	{ :mail => "cpedroza@approachmex.com", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "consultor@alester.com", :role => "distribuidor vip", :zone => "occidente" },
	{ :mail => "carlosdorantesc@prodigy.net.mx", :role => "distribuidor vip", :zone => "sur" },
	{ :mail => "carsaltelefonia@hotmail.com", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "annel_2004@hotmail.com", :role => "distribuidor vip", :zone => "occidente" },
	{ :mail => "david@cgl.mx", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "telefonica@globalred.com.mx", :role => "distribuidor vip", :zone => "occidente" },
	{ :mail => "elimerchan@relcom.com.mx", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "esteves_mariel@yahoo.com.mx", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "comglosur@yahoo.com.mx", :role => "distribuidor vip", :zone => "sur" },
	{ :mail => "alfredoespino.tps@hotmail.com", :role => "distribuidor vip", :zone => "sur" },
	{ :mail => "ecruzr@crcomunicaciones.com.mx", :role => "distribuidor vip", :zone => "sur" },
	{ :mail => "direccion@felcom.com.mx", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "fsv@satytel.com.mx", :role => "distribuidor vip", :zone => "occidente" },
	{ :mail => "tuempresaconmovistar@hotmail.com", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "grh_servicios@hotmail.com", :role => "distribuidor vip", :zone => "norte" },
	{ :mail => "gocaar1@hotmail.com", :role => "distribuidor vip", :zone => "sur" },
	{ :mail => "gsoto@asmedia.com.mx", :role => "distribuidor vip", :zone => "sur" },
	{ :mail => "karina.arellano@telefonicamoviles.com.mx", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "hflboss@hotmail.com", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "hernan.gonzalez@teknia.com.mx", :role => "distribuidor vip", :zone => "occidente" },
	{ :mail => "vallejocelulares@hotmail.com", :role => "distribuidor vip", :zone => "norte" },
	{ :mail => "israel.rodriguez@estrategiacelular.com", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "israel_calderonm@hotmail.com", :role => "distribuidor vip", :zone => "norte" },
	{ :mail => "gtemovicom@movistarmorelia.com", :role => "distribuidor vip", :zone => "occidente" },
	{ :mail => "persec@prodigy.net.mx", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "imancera@jetsocial.mx", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "yzarate2@hotmail.com", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "jacobokanan@goldencellular.com", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "ejindustrial@prodigy.net.mx", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "jaime.flores@brikale.com", :role => "distribuidor vip", :zone => "sur" },
	{ :mail => "jfernandez@star-cel.com", :role => "distribuidor vip", :zone => "norte" },
	{ :mail => "javier.diago@mobilesolutionsmexico.com", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "jbojalil@iqcalls.com.mx", :role => "distribuidor vip", :zone => "occidente" },
	{ :mail => "jbonalesc@yahoo.com.mx", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "jobe1@prodigy.net.mx", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "jorge@movilizate.com.mx", :role => "distribuidor vip", :zone => "norte" },
	{ :mail => "jocastil@gmail.com", :role => "distribuidor vip", :zone => "sur" },
	{ :mail => "jac@protecom2000.com", :role => "distribuidor vip", :zone => "norte" },
	{ :mail => "jahp1969@hotmail.com", :role => "distribuidor vip", :zone => "occidente" },
	{ :mail => "felipe@pcsmobile.com.mx", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "jlsanguino@grupomultitek.com.mx", :role => "distribuidor vip", :zone => "sur" },
	{ :mail => "sarmiento91@gmail.com", :role => "distribuidor vip", :zone => "occidente" },
	{ :mail => "jcsantos@credicousa.com", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "fcastrejon@distribuidoradetecnologia.com", :role => "distribuidor vip", :zone => "norte" },
	{ :mail => "multicevillam@hotmail.com", :role => "distribuidor vip", :zone => "occidente" },
	{ :mail => "ps_economic@hotmail.com", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "gruposagacel@hotmail.com", :role => "distribuidor vip", :zone => "occidente" },
	{ :mail => "jcperezb@pimcomunicaciones.com.mx", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "estevette@hotmail.com", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "karla.gasca@hotmail.com", :role => "distribuidor vip", :zone => "occidente" },
	{ :mail => "ecocelmoya@yahoo.com.mx", :role => "distribuidor vip", :zone => "occidente" },
	{ :mail => "kpatino@yesitel.com.mx", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "leonelvillalobos@punchmexico.com", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "celulares-semmsa@hotmail.com", :role => "distribuidor vip", :zone => "sur" },
	{ :mail => "lucio_d_h@hotmail.com", :role => "distribuidor vip", :zone => "norte" },
	{ :mail => "enamorado@prodigy.net.mx", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "lesquer@condigital.com.mx", :role => "distribuidor vip", :zone => "norte" },
	{ :mail => "lborquez@supercel.com.mx", :role => "distribuidor vip", :zone => "norte" },
	{ :mail => "luis@bcholding.com.mx", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "edsa_com@prodigy.net.mx", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "luisj@rmtecnologiamovil.com.mx", :role => "distribuidor vip", :zone => "sur" },
	{ :mail => "luis.matute@mobilesolutionsmexico.com", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "lchagra@icsicorp.com.mx", :role => "distribuidor vip", :zone => "sur" },
	{ :mail => "intercell_luis@hotmail.com", :role => "distribuidor vip", :zone => "norte" },
	{ :mail => "lmmoviltel@aol.com", :role => "distribuidor vip", :zone => "norte" },
	{ :mail => "moises.gomez@aiencomunicacion.com", :role => "distribuidor vip", :zone => "occidente" },
	{ :mail => "superplazacabo@prodigy.net.mx", :role => "distribuidor vip", :zone => "norte" },
	{ :mail => "alejandro.moreno.avila@hotmail.com", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "manuel7901@yahoo.com.mx", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "avan01@hotmail.com", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "marcobardales@mextelecom.com.mx", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "marcoleyva@movinegocios.com", :role => "distribuidor vip", :zone => "norte" },
	{ :mail => "marcos@tgmex.mx", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "mari_vivanco@hotmail.com", :role => "distribuidor vip", :zone => "occidente" },
	{ :mail => "macantabrana@hotmail.com", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "a_cuevasz@hotmail.com", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "viajeslupita@hotmail.com", :role => "distribuidor vip", :zone => "occidente" },
	{ :mail => "movinetgerencia@yahoo.com.mx", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "marianozosa2004@yahoo.com.mx", :role => "distribuidor vip", :zone => "occidente" },
	{ :mail => "mhernandez@lenna.com.mx", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "comunicasjl@hotmail.com", :role => "distribuidor vip", :zone => "occidente" },
	{ :mail => "mcastro@erurocommunique.com", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "mocell@mocell.com.mx", :role => "distribuidor vip", :zone => "occidente" },
	{ :mail => "miguel.cabrera@solmovi.com", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "mosnaya4@hotmail.com", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "ebonales@mastercel.com.mx", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "mirnarz@prodigy.net.mx", :role => "distribuidor vip", :zone => "sur" },
	{ :mail => "ncflores33@yahoo.com.mx", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "ngarcia@movilhouse.com.mx", :role => "distribuidor vip", :zone => "norte" },
	{ :mail => "rociofloress@hotmail.es", :role => "distribuidor vip", :zone => "norte" },
	{ :mail => "onelia_movistar@hotmail.com", :role => "distribuidor vip", :zone => "norte" },
	{ :mail => "oculebro@ocempresarial.com", :role => "distribuidor vip", :zone => "norte" },
	{ :mail => "pablo_sotelo@hotmail.com", :role => "distribuidor vip", :zone => "occidente" },
	{ :mail => "ppuente@vbarato.com.mx", :role => "distribuidor vip", :zone => "sur" },
	{ :mail => "movicellmadero@prodigy.net.mx", :role => "distribuidor vip", :zone => "norte" },
	{ :mail => "eleganzaejecutiva@hotmail.com", :role => "distribuidor vip", :zone => "norte" },
	{ :mail => "raymundonieto@gmail.com", :role => "distribuidor vip", :zone => "sur" },
	{ :mail => "movistarplazasanpedro@gmail.com", :role => "distribuidor vip", :zone => "norte" },
	{ :mail => "mvscellular@prodigy.net.mx", :role => "distribuidor vip", :zone => "occidente" },
	{ :mail => "ricardoenciso@gmail.com", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "ricardo.torres@mvscellular.com", :role => "distribuidor vip", :zone => "occidente" },
	{ :mail => "ricardo.xplayat@gmail.com", :role => "distribuidor vip", :zone => "sur" },
	{ :mail => "11digitos@prodigy.net.mx", :role => "distribuidor vip", :zone => "occidente" },
	{ :mail => "ilianaj@segurosavayou.com.mx", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "rrodriguez@diestel.com.mx", :role => "distribuidor vip", :zone => "norte" },
	{ :mail => "olmedo_@msn.com", :role => "distribuidor vip", :zone => "occidente" },
	{ :mail => "betochb85@hotmail.com", :role => "distribuidor vip", :zone => "norte" },
	{ :mail => "robertocarlosca@hotmail.com", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "rbmexico@gmail.com", :role => "distribuidor vip", :zone => "sur" },
	{ :mail => "polar_rodrigo@hotmail.com", :role => "distribuidor vip", :zone => "occidente" },
	{ :mail => "roalhuso@hotmail.com", :role => "distribuidor vip", :zone => "sur" },
	{ :mail => "ordo90@hotmail.com", :role => "distribuidor vip", :zone => "occidente" },
	{ :mail => "ruben.espinosa@cdigitalonline.com", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "mayrimex@hotmail.com", :role => "distribuidor vip", :zone => "sur" },
	{ :mail => "rubenbarajas@hotmail.com", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "direcciongeneral@cisagysistem.com", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "borrego@smart.net.mx", :role => "distribuidor vip", :zone => "norte" },
	{ :mail => "salvador_ruiz2001@hotmail.com", :role => "distribuidor vip", :zone => "norte" },
	{ :mail => "smontano@live.com.mx", :role => "distribuidor vip", :zone => "occidente" },
	{ :mail => "sandyemiuruapan@yahoo.com.mx", :role => "distribuidor vip", :zone => "occidente" },
	{ :mail => "sburgos@communique.com.mx", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "sergioxtreme@prodigy.net.mx", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "sergio_ortega_alvarez@yahoo.com.mx", :role => "distribuidor vip", :zone => "sur" },
	{ :mail => "svillarreal@tecnologiacelular.com.mx", :role => "distribuidor vip", :zone => "norte" },
	{ :mail => "sue.a.villalobos@gmail.com", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "tflores@cspmovil.com.mx", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "vems82@hotmail.com", :role => "distribuidor vip", :zone => "occidente" },
	{ :mail => "gutvd@mtcenter.com.mx", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "vhchaher@hotmail.com", :role => "distribuidor vip", :zone => "occidente" },
	{ :mail => "rastreogps@hotmail.com", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "soluciones.globales@yahoo.com.mx", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "victor@tintamaxqdl.com", :role => "distribuidor vip", :zone => "occidente" },
	{ :mail => "viter75@yahoo.com.mx", :role => "distribuidor vip", :zone => "sur" },
	{ :mail => "tadistribucion@live.com.mx", :role => "distribuidor vip", :zone => "sur" },
	{ :mail => "jlgonpal@hotmail.com", :role => "distribuidor vip", :zone => "occidente" },
	{ :mail => "ymizrahi@digitalcity.com.mx", :role => "distribuidor vip", :zone => "centro" },
	{ :mail => "promotelzc@yahoo.com", :role => "distribuidor vip", :zone => "norte" },
	{ :mail => "alexsanc88@hotmail.com", :role => "experto", :zone => "sur" },
	{ :mail => "alypauly@hotmail.com y", :role => "experto", :zone => "norte" },
	{ :mail => "angeltomi@live.com.mx", :role => "experto", :zone => "occidente" },
	{ :mail => "leoncita_china1985@hotmail.com", :role => "experto", :zone => "sur" },
	{ :mail => "fabiolahea@hotmail.com", :role => "experto", :zone => "occidente" },
	{ :mail => "cecy_princesitarg@hotmail.com", :role => "experto", :zone => "norte" },
	{ :mail => "cinthya_galle19@hotmail.com", :role => "experto", :zone => "occidente" },
	{ :mail => "cristian.1545a@hotmail.com", :role => "experto", :zone => "centro" },
	{ :mail => "corral.e@hotmail.com", :role => "experto", :zone => "norte" },
	{ :mail => "gerar_1719@hotmail.com", :role => "experto", :zone => "sur" },
	{ :mail => "trujano@celsur.com.mx", :role => "experto", :zone => "sur" },
	{ :mail => "jhj_7@hotmail.com", :role => "experto", :zone => "norte" },
	{ :mail => "karla_xtreme@hotmail.com", :role => "experto", :zone => "occidente" },
	{ :mail => "lewer_lirin@hotmail.com", :role => "experto", :zone => "occidente" },
	{ :mail => "marlenemuv@live.com.mx", :role => "experto", :zone => "occidente" },
	{ :mail => "luicho_8@yahoo.com.mx", :role => "experto", :zone => "occidente" },
	{ :mail => "alex_caczacatecas@hotmail.com", :role => "experto", :zone => "occidente" },
	{ :mail => "omar_rothenbucker@hotmail.com", :role => "experto", :zone => "norte" },
	{ :mail => "omar_comi90@hotmail.com", :role => "experto", :zone => "sur" },
	{ :mail => "perla_gabygordillo@hotmail.com", :role => "experto", :zone => "norte" },
	{ :mail => "elizabeth.cruz@telefonica.com.mx", :role => "supervisor", :zone => "sur" },
	{ :mail => "gustavo.lopez.ext@telefonica.com", :role => "supervisor", :zone => "centro" },
	{ :mail => "jorge.pedregal.ext@telefonica.com", :role => "supervisor", :zone => "centro" },
	{ :mail => "josel.ortiz.ext@telefonica.com", :role => "supervisor", :zone => "centro" },
	{ :mail => "karina.bautista.ext@telefonica.com", :role => "supervisor", :zone => "centro" },
	{ :mail => "lisseth.castro@telefonica.com", :role => "supervisor", :zone => "sur" },
	{ :mail => "mariadelcarmen.bonilla.ext@telefonica.com", :role => "supervisor", :zone => "centro" },
	{ :mail => "maria.jacobo.ext@telefonica.com", :role => "supervisor", :zone => "centro" },
	{ :mail => "marthab.lopez@telefonica.com", :role => "supervisor", :zone => "centro" },
	{ :mail => "mrcm_35@hotmail.com", :role => "supervisor", :zone => "norte" },
	{ :mail => "oo7estrada@hotmail.com", :role => "supervisor", :zone => "centro" },
	{ :mail => "l_serch@hotmail.com", :role => "supervisor", :zone => "centro" },
	{ :mail => "jesusdelgado105@hotmail.com", :role => "vendedor", :zone => "sur" },
	{ :mail => "jesusdelgado105@hotmail.com", :role => "vendedor", :zone => "sur" },
	{ :mail => "abeltim@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "movicelltodosantos@gmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "aidee_cristina@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "katy.key18@gmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "dulce_jezli@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "jose.camacho.ext@telefonica.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "akbc_0691@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "andr3s@live.com.mx", :role => "vendedor", :zone => "occidente" },
	{ :mail => "angycon_20@hotmail.com", :role => "vendedor", :zone => "sur" },
	{ :mail => "bbsita_sex91@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "movistarloreto@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "charlyvivancovida@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "carlosgonzalezlopez@yahoo.com.mx", :role => "vendedor", :zone => "occidente" },
	{ :mail => "carlfed57@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "cecy-@live.com.mx", :role => "vendedor", :zone => "norte" },
	{ :mail => "sertecamac1@solmovi.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "inmotion20@gmail.com", :role => "vendedor", :zone => "#n/a" },
	{ :mail => "mundomovilelgrullo@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "cosiitthasraras@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "citlali.sanchezc.ext@telefonica.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "claopetia@hotmail.com", :role => "vendedor", :zone => "#n/a" },
	{ :mail => "crisa_32@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "nohemi_24_zac@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "declancerecero@gmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "cristy_vdl@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "cynthiakarinabarbaboites@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "festigrullo@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "danifresy_1000@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "dygustavo_17@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "olvido2205@hotmail.com", :role => "vendedor", :zone => "sur" },
	{ :mail => "omar_s_rivas@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "catedralplazamovistar@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "deliavillasol@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "vcadmon@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "tiendahuehuetoca@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "tsenderolinconmty@tecnologiacelular.com.mx", :role => "vendedor", :zone => "norte" },
	{ :mail => "dkgalloso@gmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "diana_arleth15@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "ibeth-soto@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "deluxeautlan@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "dinausashoes@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "edith_5415@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "isla_coacalco@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "karlajudithherrera@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "dulc.mitzi@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "dmendez@multicel.com.mx", :role => "vendedor", :zone => "sur" },
	{ :mail => "plaza.izcalli@mobilesolutionsmexico.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "rko.edge@live.com.mx", :role => "vendedor", :zone => "centro" },
	{ :mail => "etggjuarez@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "edgar_ferrari_15@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "bedlith@yahoo.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "erika_edy2628@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "erika_edy_2628@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "ik_pz@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "ezepeda@solutecno.mx", :role => "vendedor", :zone => "sur" },
	{ :mail => "eduardo_cooss@hotmail.com", :role => "vendedor", :zone => "sur" },
	{ :mail => "eduardo_1990@live.com.mx", :role => "vendedor", :zone => "occidente" },
	{ :mail => "plazaoriente@xacell.com.mx", :role => "vendedor", :zone => "sur" },
	{ :mail => "esilvachaparro@gmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "laloxtlan@hotmail.com", :role => "vendedor", :zone => "sur" },
	{ :mail => "j_e_125@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "eduardolopezcarreon@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "true_lalo@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "hebaztlan@star-cel.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "eleazar_1391@hotmail.com", :role => "vendedor", :zone => "sur" },
	{ :mail => "nime26-@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "fosilusk69@gmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "elisasalinassalinas@yahoo.com.mx", :role => "vendedor", :zone => "sur" },
	{ :mail => "movicom_lazaro1910@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "sacika_666@hotmail.com", :role => "vendedor", :zone => "sur" },
	{ :mail => "sucursalixtapa@jetsocial.mx", :role => "vendedor", :zone => "occidente" },
	{ :mail => "elizanov21@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "princesita41085@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "liznigga@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "elysmile18@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "elizabeth.jimenez@cissa-mex.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "emidi23@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "la chapis_91@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "eljardinregalado@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "ebarreramoviles@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "arifer_17@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "movistar_tena@yahoo.com.mx", :role => "vendedor", :zone => "centro" },
	{ :mail => "oilime64@hotmail.com", :role => "vendedor", :zone => "sur" },
	{ :mail => "coffe_037@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "enrique-44@live.com.mx", :role => "vendedor", :zone => "occidente" },
	{ :mail => "con_tec04@yahoo.com.mx", :role => "vendedor", :zone => "occidente" },
	{ :mail => "rosakik@live.com.mx", :role => "vendedor", :zone => "centro" },
	{ :mail => "jerkicw@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "pcsexpress1@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "erikab_18_@hotmail.com", :role => "vendedor", :zone => "sur" },
	{ :mail => "tecnologia@solutecno.mx", :role => "vendedor", :zone => "sur" },
	{ :mail => "b0lenna@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "lerik_g@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "ecarmona7519@yahoo.com.mx", :role => "vendedor", :zone => "centro" },
	{ :mail => "erika_iusa@hotmail.com", :role => "vendedor", :zone => "sur" },
	{ :mail => "sweet_love0407@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "negro13loko@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "pumpkinton@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "hebes@tododigital.com.mx", :role => "vendedor", :zone => "norte" },
	{ :mail => "esmeralda.jaime.ext@telefonica.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "stefhan-y1994@hotmail.com", :role => "vendedor", :zone => "sur" },
	{ :mail => "cumbrespn@star-cel.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "no_ev@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "evr_2525@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "tanys06_@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "alexius_284sp@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "rdz_mayanin@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "rinocel@gmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "felipeaelohim@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "beatiful_jare@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "fernando_sidermisa@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "jordan_rostro@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "florhermoxa.29@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "florkazandra@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "quika_rrios@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "franciscoflores852@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "refaccionariadrosadomuna@hotmail.com", :role => "vendedor", :zone => "sur" },
	{ :mail => "frackvalalv78@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "ciber_cell_12@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "paco_garcia777@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "frank_942011@hotmailo.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "javier_cancer@hotmail.com", :role => "vendedor", :zone => "sur" },
	{ :mail => "islalaurovillarmat@tecnologiacelular.com.mx", :role => "vendedor", :zone => "norte" },
	{ :mail => "jrodriguez@jetsocial.mx", :role => "vendedor", :zone => "occidente" },
	{ :mail => "islacampestrevictoria@tecnologiacelular.com.mx", :role => "vendedor", :zone => "norte" },
	{ :mail => "tienda14victoria@tecnologiacelular.com.mx", :role => "vendedor", :zone => "norte" },
	{ :mail => "purgogab@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "danielito465@gmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "gflores@multicel.com.mx", :role => "vendedor", :zone => "sur" },
	{ :mail => "ana_gaby_8617_@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "gabyy_xtreme@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "gabylopezrdz@yahoo.com.mx", :role => "vendedor", :zone => "centro" },
	{ :mail => "genaro0_fsm@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "almaguerpumas@gmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "germanjvc14@gmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "mascaradelamuerte@hotmail.com", :role => "vendedor", :zone => "sur" },
	{ :mail => "gilberto.morales@cissa-mex.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "li951_45@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "gorgoch64@gmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "planescentro@gmail.com", :role => "vendedor", :zone => "sur" },
	{ :mail => "estrella.glo@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "arge_20_lia@yahoo.com.mx", :role => "vendedor", :zone => "centro" },
	{ :mail => "griss_bere@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "b_bitachila_88@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "guadalupesalinashernandez@yahoo.com.mx", :role => "vendedor", :zone => "sur" },
	{ :mail => "mghr_100@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "ciber_digymax@yahoo.com.mx", :role => "vendedor", :zone => "occidente" },
	{ :mail => "guielljr12@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "tiendalaurovillar2@tecnologiacelular.com.mx", :role => "vendedor", :zone => "norte" },
	{ :mail => "gpedrajo@yahoo.com.mx", :role => "vendedor", :zone => "occidente" },
	{ :mail => "cocol26@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "star-024@solmovi.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "gustavogvalencia@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "tio_aguila@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "tavopasion@gmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "madero.mty@cissa-mex.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "hector_joven@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "sorianapn@star-cel.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "ivanrh21@live.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "ivanrh21@hotmail.es", :role => "vendedor", :zone => "occidente" },
	{ :mail => "ventashcruz@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "nanin-salazar@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "hernan_fernando158@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "enamorado_hilda@yahoo.com", :role => "vendedor", :zone => "sur" },
	{ :mail => "hiram_arellano@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "hita-102@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "hcoronado@jetsocial.mx", :role => "vendedor", :zone => "occidente" },
	{ :mail => "hugolabamba@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "fhgarzamoreno@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "h_sant7@hotmail.com", :role => "vendedor", :zone => "sur" },
	{ :mail => "leona_reyna@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "isabelramos704@gmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "maldita.seas666@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "isela_isaguirre@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "ismapoli_95@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "idr1982@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "iivan_alonso@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "ivan_aguilas_1712@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "puccaescorpion@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "ivonne-xtreme@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "ivonne_ztrada@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "tigrex_23@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "jahir_2060@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "moduloelcampesinovictoria@tecnologiacelular.com.mx", :role => "vendedor", :zone => "norte" },
	{ :mail => "havii3r_samz@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "javierhdeza@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "tiendasunmall@tecnologiacelular.com.mx", :role => "vendedor", :zone => "norte" },
	{ :mail => "jennycfn@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "power_edgar16@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "israel.bracamontes@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "omaro09amor@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "olisas22@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "tiendalagunetamat@tecnologiacelular.com.mx", :role => "vendedor", :zone => "norte" },
	{ :mail => "jesusmontelongollamas@gmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "jesus.alonso.oropeza@hotmail.com", :role => "vendedor", :zone => "sur" },
	{ :mail => "cancerr2k.vdln@hotmail.com", :role => "vendedor", :zone => "sur" },
	{ :mail => "desbloqueosemblematica@star-cel.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "jasiel_loav09@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "je_rangel@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "jesus_tmpr@hotmail.com", :role => "vendedor", :zone => "sur" },
	{ :mail => "jeucolmenaresmendez@gmail.com", :role => "vendedor", :zone => "sur" },
	{ :mail => "ckristal_53@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "johny_a.j.arellano@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "jogahego@gmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "boonejorge@cissa-mex.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "esau_villa06@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "ekoko_@hotmail.com", :role => "vendedor", :zone => "sur" },
	{ :mail => "mtysendero@diestel.com.mx", :role => "vendedor", :zone => "norte" },
	{ :mail => "regioalcala@gmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "jfsantiagomoviles@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "itsvan75@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "cellventa3@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "jg_cowboys@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "jrvargas83@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "jmoragar01@yahoo.com.mx", :role => "vendedor", :zone => "occidente" },
	{ :mail => "tlindavistamty@tecnologiacelular.com.mx", :role => "vendedor", :zone => "norte" },
	{ :mail => "ppsantiago26@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "elyeyopotro@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "kilajaf@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "dahiky_extreme_666@hotmail.com", :role => "vendedor", :zone => "sur" },
	{ :mail => "caos_david@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "eduardomorley@gmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "fjuarez_81@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "gygtelefonica@gmail.com", :role => "vendedor", :zone => "sur" },
	{ :mail => "jose.gpe@mastercell.com.mx", :role => "vendedor", :zone => "occidente" },
	{ :mail => "jayala@solutecno.mx", :role => "vendedor", :zone => "sur" },
	{ :mail => "nesacom@gmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "l.u.i.s.coml@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "luis.movistar07@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "arxom@yahoo.com.mx", :role => "vendedor", :zone => "occidente" },
	{ :mail => "luis_d7@vista.aero", :role => "vendedor", :zone => "occidente" },
	{ :mail => "chema32@live.com.mx", :role => "vendedor", :zone => "centro" },
	{ :mail => "sannicolas.monterrey@cissa-mex.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "renevillavicencio@live.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "josue310379@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "nambo25@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "juangonzalezrami@live.com.mx", :role => "vendedor", :zone => "centro" },
	{ :mail => "jangelsg7@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "satelite@digitalcity.com.mx", :role => "vendedor", :zone => "centro" },
	{ :mail => "charly_buru@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "1_alo_93@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "juanchoprieto@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "j-g-a-l@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "juan22_ojeda@hotmail.com", :role => "vendedor", :zone => "sur" },
	{ :mail => "cissahebchapultepec@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "juan_jose_reyes_1990@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "kingrap_618@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "promotoresmovistarautlan@gmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "jmanuelcompiro@gmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "coby010229@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "tiendasenderoapodaca@tecnologiacelular.com.mx", :role => "vendedor", :zone => "norte" },
	{ :mail => "escobedo.mty@cissa-mex.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "recargas_mastercel@hotmail.com", :role => "vendedor", :zone => "sur" },
	{ :mail => "krm_xtreme@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "deavilardz_28@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "movivillas@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "mc.oaxaca@hotmail.com", :role => "vendedor", :zone => "sur" },
	{ :mail => "ysa.reyes@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "klobatog@yahoo.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "lobato2009@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "karinarg91@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "comunicajalos@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "kari_ro69@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "karinaelizabeth..13@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "anirak_yek@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "chicab3@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "renata071008@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "dora.1590@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "karla.bher@gmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "kenda_osorio@hotmail.com", :role => "vendedor", :zone => "sur" },
	{ :mail => "dmonterrey.ventas@oiracel.com.mx", :role => "vendedor", :zone => "norte" },
	{ :mail => "bokutachi_@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "gkitziacecilia@yahoo.com.mx", :role => "vendedor", :zone => "centro" },
	{ :mail => "lauris_87@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "emonterrey-ventas@oiracel.com.mx", :role => "vendedor", :zone => "norte" },
	{ :mail => "lauraml0307@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "laura_2810@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "laura-lara_nautilus@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "cam2804@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "chaparrita_pesosa@hotmail.com", :role => "vendedor", :zone => "sur" },
	{ :mail => "precious_91@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "ela.002@live.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "damian_8304@hotmail.com", :role => "vendedor", :zone => "sur" },
	{ :mail => "leslie881@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "tiendacentrikamty@tecnologiacelular.com.mx", :role => "vendedor", :zone => "norte" },
	{ :mail => "yuli.starblack@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "isolda_galvez@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "ventasmovimad@yahoo.com.mx", :role => "vendedor", :zone => "sur" },
	{ :mail => "myriamflores@live.com.mx", :role => "vendedor", :zone => "norte" },
	{ :mail => "blitzel_4689@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "lizeth.rojas.ext@telefonica.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "mapache_96@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "alb_zoe_lizzy@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "lloeni_coppel270183@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "lore_cid@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "jesusmunis1@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "lullusa26@yahoo.com.mx", :role => "vendedor", :zone => "centro" },
	{ :mail => "luz_nice_new@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "ludypepe@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "lugavel@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "monicasalamun@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "goyo-92@lite.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "cyc_elvaqueronorteno@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "luislozano1980@gmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "luisenriquecast@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "pendragon_heaven@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "fernando_montoya_1a_fdl@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "light_may2@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "luz_dcav@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "lept01@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "luzmariel_24@hotmail.com", :role => "vendedor", :zone => "sur" },
	{ :mail => "chapulynn1@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "lachulis_85@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "mrz-cuquis@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "marcela_yazmin_b@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "maesquivel@gmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "licmosso@gmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "nmcm2@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "marybutik@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "hermaryji_456@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "malurem@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "mmercardoarroyo@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "mmateo@live.com.mx", :role => "vendedor", :zone => "centro" },
	{ :mail => "mac-k35@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "islasb@star-cel.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "valdezmarydani@hotmail.com.mx", :role => "vendedor", :zone => "occidente" },
	{ :mail => "maria.salas.ext@telefonica.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "sotin007@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "chelsywer@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "gcdrossy@yahoo.com.mx", :role => "vendedor", :zone => "centro" },
	{ :mail => "eliza210394@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "m_maria1992@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "fer.esparza001@gmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "albertflores@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "lupis_smart3011@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "pita_ramos_28@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "tkiero_blu@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "mzamarripasaucedo@yahoo.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "edith-1212@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "mv-gh@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "vcalmacen@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "mariherrera@yahoo.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "telefonicaexpress@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "maricelafm86@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "maricruz_lokka@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "ballesterosmario1@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "marichis_majik19@live.com.mx", :role => "vendedor", :zone => "occidente" },
	{ :mail => "movistar.tsantos@prodigy.net.mx", :role => "vendedor", :zone => "norte" },
	{ :mail => "amarlem_@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "martha_ruizlu@hotmail.es", :role => "vendedor", :zone => "centro" },
	{ :mail => "mafrados1377@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "tiendavallesoleado@tecnologiacelular.com.mx", :role => "vendedor", :zone => "norte" },
	{ :mail => "rock_soniko@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "cdpymes_mavy@hotmail.com", :role => "vendedor", :zone => "sur" },
	{ :mail => "abelita_16@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "cd_sin_limite@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "amor_fresa_94@hotmail.com", :role => "vendedor", :zone => "sur" },
	{ :mail => "mayra.romero.ext@telefonica.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "magui1908@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "mayra.22@live.com.mx", :role => "vendedor", :zone => "occidente" },
	{ :mail => "maypoe@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "melywoman_007@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "mercy2271@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "michi_0626@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "mixelitha@live.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "fusion_uribe06@hotmail.com", :role => "vendedor", :zone => "sur" },
	{ :mail => "benlli_333@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "mickyjam_23@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "chicab_streshita@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "misaki.black@live.com.mx", :role => "vendedor", :zone => "occidente" },
	{ :mail => "miriam.valencia.ext@telefonica.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "mirukys@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "essapryncessazteca13@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "mirgo165@gmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "miriam.medina@msm.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "mitzi_og03@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "mopet222@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "winterblue35@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "moy_gzz@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "monica.suarez.gutierrez11@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "texcoco@solmovi.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "pucca_06@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "monica.lunna_@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "moni_kgv@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "monzita_yop@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "moonsrainbow@hotmail.com", :role => "vendedor", :zone => "sur" },
	{ :mail => "chaparrita111090@gmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "madile68@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "morfis_86@yahoo.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "nancy_15chitilla@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "tiendasenderomat@tecnologiacelular.com.mx", :role => "vendedor", :zone => "norte" },
	{ :mail => "nancy.cc18@gmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "cusur_9103@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "melth_22@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "nancy.flaca@live.com.mx", :role => "vendedor", :zone => "centro" },
	{ :mail => "fashionstar-nayeli@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "trmenda_mary@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "neftali_00788@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "elfen_lied_nyu@live.com.mx", :role => "vendedor", :zone => "sur" },
	{ :mail => "narce39@gmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "euphorianex@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "nhess.espinoza@yahoo.com.mx", :role => "vendedor", :zone => "sur" },
	{ :mail => "islaapodaca@tecnologiacelular.com.mx", :role => "vendedor", :zone => "norte" },
	{ :mail => "lucio@celsur.com.mx", :role => "vendedor", :zone => "sur" },
	{ :mail => "digitalrubio@live.com.mx", :role => "vendedor", :zone => "occidente" },
	{ :mail => "noelsa-yazmin11@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "princez_damn@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "noemidelalima@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "nohemi.lopez.ext@telefonica.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "noras_2310@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "angelica_aleman_87@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "normaaberino@hotmail.es", :role => "vendedor", :zone => "norte" },
	{ :mail => "momis_movi@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "norma_movitam@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "normis_ara@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "liely_726@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "gohs1305@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "romo8703@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "oct_chivas@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "omar.villamayor.ext@telefonica.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "hvcelulares@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "isla35lincolnmty@tecnologiacelular.com.mx", :role => "vendedor", :zone => "norte" },
	{ :mail => "pachecoomar440@gmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "alexis_campeon_1@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "oscar.ocelotl@gmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "oscar2000rv@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "calmecac07@gmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "oscar_100292@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "xteck@live.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "the.saga@gmail.com", :role => "vendedor", :zone => "sur" },
	{ :mail => "torodos@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "mercopiedrasnegras@star-cel.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "pathithahdz@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "patitamaravilla@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "patyavina_74@hhotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "y_fresita_23@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "paulina.belanova@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "paulina.cuahutle.ext@telefonica.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "mustang-burbuja@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "lopezyaz@gmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "lesmusselove@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "perla_zapata@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "rafael.gamboa.ext@telefonica.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "hoker_2013@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "rafaelsave.850918@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "mago_jogabonito10@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "rebeca82_3@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "leo_ley52@hotmail.com", :role => "vendedor", :zone => "sur" },
	{ :mail => "melchor40@live.com", :role => "vendedor", :zone => "sur" },
	{ :mail => "hidalgocentro2@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "rnpu316@hotmail.com", :role => "vendedor", :zone => "sur" },
	{ :mail => "arriozolaperales@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "rickysias123@gmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "rich_lul@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "sanchezvelasquezroberto@gmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "ideke_740@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "rocio.compostela@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "chio_080688@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "gvallejo@star-cel.com.mx", :role => "vendedor", :zone => "norte" },
	{ :mail => "vick_rei90@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "linda.amscell@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "rox.ara86@gmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "rosy_eimi@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "rosario.ortiz@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "paulita_8a@live.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "ramat@condigital.com.mx", :role => "vendedor", :zone => "norte" },
	{ :mail => "deyanira_loki86@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "rulis.c.ok@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "pakogrt_@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "r_naomi2010@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "salazulcv@yahoo.com.mx", :role => "vendedor", :zone => "occidente" },
	{ :mail => "chabalala58@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "esmedinag@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "antiparo@gmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "mtysendero2@diestel.com.mx", :role => "vendedor", :zone => "norte" },
	{ :mail => "sammo.santiago@gmail.com", :role => "vendedor", :zone => "sur" },
	{ :mail => "sendero@tododigital.com.mx", :role => "vendedor", :zone => "norte" },
	{ :mail => "sandra14819@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "bombon2871@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "salumopa@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "elisamovistar@hotmail.com", :role => "vendedor", :zone => "sur" },
	{ :mail => "saracolin_2010@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "oyuki_sarai@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "krma_lanny30@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "selene.guerra@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "ariadna.ecocel@gmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "sergio.munoz800@gmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "sguzman@jetsocial.mx", :role => "vendedor", :zone => "occidente" },
	{ :mail => "sergio_lobo888@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "sharon_rmz94@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "little_sexygirl140@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "silviaacuario76@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "nexx.ruiz@gmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "sofis_3092@hotmail.com", :role => "vendedor", :zone => "sur" },
	{ :mail => "sonyexitosa09@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "supervision_sonia@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "grupo-montcerv@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "f_l_aakitabebe15@hotmail.com", :role => "vendedor", :zone => "sur" },
	{ :mail => "ainath_luna@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "ainat21@live.com.mx", :role => "vendedor", :zone => "norte" },
	{ :mail => "trini.trinitaria@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "satanika196@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "valentin73@live.com.mx", :role => "vendedor", :zone => "norte" },
	{ :mail => "amonterrey.ventas@oiracel.com.mx", :role => "vendedor", :zone => "norte" },
	{ :mail => "heb.nogalera.cac@cissa-mex.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "muebleracolchorama@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "vero_anix35@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "alexa.vianey@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "tiendalafe1@diestel.com.mx", :role => "vendedor", :zone => "norte" },
	{ :mail => "vazquez_0687@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "eduar_mora@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "viczendo_@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "victora.hernandez.ext@telefonica.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "victor.bautista.ext@telefonica.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "vtomanueln19@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "violeta_g31@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "viri-libra_@live.com.mx", :role => "vendedor", :zone => "sur" },
	{ :mail => "liliana917@msn.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "yady_97@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "yairsicaru@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "yazmin_torres_13@hotmail.com", :role => "vendedor", :zone => "centro" },
	{ :mail => "yenita@live.com.mx", :role => "vendedor", :zone => "centro" },
	{ :mail => "yeymamartinez@hormail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "yesicaloka@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "yessica_alejandro@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "yessicaenzacta@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "yolandadiaz124@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "yori_paco@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "yosajandy.amscell@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "movilagos_comunica@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "yulma_planetcel@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "yuriko_533@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "zaira_zorro@hotmail.com", :role => "vendedor", :zone => "occidente" },
	{ :mail => "zitamendoza78@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "zitamendoza78@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "zitamendoza78@hotmail.com", :role => "vendedor", :zone => "norte" },
	{ :mail => "leon.merol@gmail.com", :role => "#n/a", :zone => "#n/a" },
	{ :mail => "leon.merol+10@gmail.com", :role => "#n/a", :zone => "#n/a" },
	{ :mail => "leon.merol+77@gmail.com", :role => "#n/a", :zone => "#n/a" }]

  csv_users.each do |user|
    mail = user[:mail]
    tmp_user = User.find_by_email(mail)
      if tmp_user.nil?
        puts "warning: usuario no encontrado => " + mail
      else
        tmp_user.telefonica_role=user[:role]
        tmp_user.telefonica_zone=user[:zone]
        tmp_user.save!
      end
  end
end
