require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AcceptedTermsController do

  # This should return the minimal set of attributes required to create a valid
  # AcceptedTerm. As you add validations to AcceptedTerm, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AcceptedTermsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all accepted_terms as @accepted_terms" do
      accepted_term = AcceptedTerm.create! valid_attributes
      get :index, {}, valid_session
      assigns(:accepted_terms).should eq([accepted_term])
    end
  end

  describe "GET show" do
    it "assigns the requested accepted_term as @accepted_term" do
      accepted_term = AcceptedTerm.create! valid_attributes
      get :show, {:id => accepted_term.to_param}, valid_session
      assigns(:accepted_term).should eq(accepted_term)
    end
  end

  describe "GET new" do
    it "assigns a new accepted_term as @accepted_term" do
      get :new, {}, valid_session
      assigns(:accepted_term).should be_a_new(AcceptedTerm)
    end
  end

  describe "GET edit" do
    it "assigns the requested accepted_term as @accepted_term" do
      accepted_term = AcceptedTerm.create! valid_attributes
      get :edit, {:id => accepted_term.to_param}, valid_session
      assigns(:accepted_term).should eq(accepted_term)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AcceptedTerm" do
        expect {
          post :create, {:accepted_term => valid_attributes}, valid_session
        }.to change(AcceptedTerm, :count).by(1)
      end

      it "assigns a newly created accepted_term as @accepted_term" do
        post :create, {:accepted_term => valid_attributes}, valid_session
        assigns(:accepted_term).should be_a(AcceptedTerm)
        assigns(:accepted_term).should be_persisted
      end

      it "redirects to the created accepted_term" do
        post :create, {:accepted_term => valid_attributes}, valid_session
        response.should redirect_to(AcceptedTerm.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved accepted_term as @accepted_term" do
        # Trigger the behavior that occurs when invalid params are submitted
        AcceptedTerm.any_instance.stub(:save).and_return(false)
        post :create, {:accepted_term => {}}, valid_session
        assigns(:accepted_term).should be_a_new(AcceptedTerm)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AcceptedTerm.any_instance.stub(:save).and_return(false)
        post :create, {:accepted_term => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested accepted_term" do
        accepted_term = AcceptedTerm.create! valid_attributes
        # Assuming there are no other accepted_terms in the database, this
        # specifies that the AcceptedTerm created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AcceptedTerm.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => accepted_term.to_param, :accepted_term => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested accepted_term as @accepted_term" do
        accepted_term = AcceptedTerm.create! valid_attributes
        put :update, {:id => accepted_term.to_param, :accepted_term => valid_attributes}, valid_session
        assigns(:accepted_term).should eq(accepted_term)
      end

      it "redirects to the accepted_term" do
        accepted_term = AcceptedTerm.create! valid_attributes
        put :update, {:id => accepted_term.to_param, :accepted_term => valid_attributes}, valid_session
        response.should redirect_to(accepted_term)
      end
    end

    describe "with invalid params" do
      it "assigns the accepted_term as @accepted_term" do
        accepted_term = AcceptedTerm.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AcceptedTerm.any_instance.stub(:save).and_return(false)
        put :update, {:id => accepted_term.to_param, :accepted_term => {}}, valid_session
        assigns(:accepted_term).should eq(accepted_term)
      end

      it "re-renders the 'edit' template" do
        accepted_term = AcceptedTerm.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AcceptedTerm.any_instance.stub(:save).and_return(false)
        put :update, {:id => accepted_term.to_param, :accepted_term => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested accepted_term" do
      accepted_term = AcceptedTerm.create! valid_attributes
      expect {
        delete :destroy, {:id => accepted_term.to_param}, valid_session
      }.to change(AcceptedTerm, :count).by(-1)
    end

    it "redirects to the accepted_terms list" do
      accepted_term = AcceptedTerm.create! valid_attributes
      delete :destroy, {:id => accepted_term.to_param}, valid_session
      response.should redirect_to(accepted_terms_url)
    end
  end

end
