require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CalificationemsController do

  # This should return the minimal set of attributes required to create a valid
  # Calificationem. As you add validations to Calificationem, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CalificationemsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all calificationems as @calificationems" do
      calificationem = Calificationem.create! valid_attributes
      get :index, {}, valid_session
      assigns(:calificationems).should eq([calificationem])
    end
  end

  describe "GET show" do
    it "assigns the requested calificationem as @calificationem" do
      calificationem = Calificationem.create! valid_attributes
      get :show, {:id => calificationem.to_param}, valid_session
      assigns(:calificationem).should eq(calificationem)
    end
  end

  describe "GET new" do
    it "assigns a new calificationem as @calificationem" do
      get :new, {}, valid_session
      assigns(:calificationem).should be_a_new(Calificationem)
    end
  end

  describe "GET edit" do
    it "assigns the requested calificationem as @calificationem" do
      calificationem = Calificationem.create! valid_attributes
      get :edit, {:id => calificationem.to_param}, valid_session
      assigns(:calificationem).should eq(calificationem)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Calificationem" do
        expect {
          post :create, {:calificationem => valid_attributes}, valid_session
        }.to change(Calificationem, :count).by(1)
      end

      it "assigns a newly created calificationem as @calificationem" do
        post :create, {:calificationem => valid_attributes}, valid_session
        assigns(:calificationem).should be_a(Calificationem)
        assigns(:calificationem).should be_persisted
      end

      it "redirects to the created calificationem" do
        post :create, {:calificationem => valid_attributes}, valid_session
        response.should redirect_to(Calificationem.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved calificationem as @calificationem" do
        # Trigger the behavior that occurs when invalid params are submitted
        Calificationem.any_instance.stub(:save).and_return(false)
        post :create, {:calificationem => {}}, valid_session
        assigns(:calificationem).should be_a_new(Calificationem)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Calificationem.any_instance.stub(:save).and_return(false)
        post :create, {:calificationem => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested calificationem" do
        calificationem = Calificationem.create! valid_attributes
        # Assuming there are no other calificationems in the database, this
        # specifies that the Calificationem created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Calificationem.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => calificationem.to_param, :calificationem => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested calificationem as @calificationem" do
        calificationem = Calificationem.create! valid_attributes
        put :update, {:id => calificationem.to_param, :calificationem => valid_attributes}, valid_session
        assigns(:calificationem).should eq(calificationem)
      end

      it "redirects to the calificationem" do
        calificationem = Calificationem.create! valid_attributes
        put :update, {:id => calificationem.to_param, :calificationem => valid_attributes}, valid_session
        response.should redirect_to(calificationem)
      end
    end

    describe "with invalid params" do
      it "assigns the calificationem as @calificationem" do
        calificationem = Calificationem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Calificationem.any_instance.stub(:save).and_return(false)
        put :update, {:id => calificationem.to_param, :calificationem => {}}, valid_session
        assigns(:calificationem).should eq(calificationem)
      end

      it "re-renders the 'edit' template" do
        calificationem = Calificationem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Calificationem.any_instance.stub(:save).and_return(false)
        put :update, {:id => calificationem.to_param, :calificationem => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested calificationem" do
      calificationem = Calificationem.create! valid_attributes
      expect {
        delete :destroy, {:id => calificationem.to_param}, valid_session
      }.to change(Calificationem, :count).by(-1)
    end

    it "redirects to the calificationems list" do
      calificationem = Calificationem.create! valid_attributes
      delete :destroy, {:id => calificationem.to_param}, valid_session
      response.should redirect_to(calificationems_url)
    end
  end

end
