require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CommentPostsController do

  # This should return the minimal set of attributes required to create a valid
  # CommentPost. As you add validations to CommentPost, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CommentPostsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all comment_posts as @comment_posts" do
      comment_post = CommentPost.create! valid_attributes
      get :index, {}, valid_session
      assigns(:comment_posts).should eq([comment_post])
    end
  end

  describe "GET show" do
    it "assigns the requested comment_post as @comment_post" do
      comment_post = CommentPost.create! valid_attributes
      get :show, {:id => comment_post.to_param}, valid_session
      assigns(:comment_post).should eq(comment_post)
    end
  end

  describe "GET new" do
    it "assigns a new comment_post as @comment_post" do
      get :new, {}, valid_session
      assigns(:comment_post).should be_a_new(CommentPost)
    end
  end

  describe "GET edit" do
    it "assigns the requested comment_post as @comment_post" do
      comment_post = CommentPost.create! valid_attributes
      get :edit, {:id => comment_post.to_param}, valid_session
      assigns(:comment_post).should eq(comment_post)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CommentPost" do
        expect {
          post :create, {:comment_post => valid_attributes}, valid_session
        }.to change(CommentPost, :count).by(1)
      end

      it "assigns a newly created comment_post as @comment_post" do
        post :create, {:comment_post => valid_attributes}, valid_session
        assigns(:comment_post).should be_a(CommentPost)
        assigns(:comment_post).should be_persisted
      end

      it "redirects to the created comment_post" do
        post :create, {:comment_post => valid_attributes}, valid_session
        response.should redirect_to(CommentPost.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved comment_post as @comment_post" do
        # Trigger the behavior that occurs when invalid params are submitted
        CommentPost.any_instance.stub(:save).and_return(false)
        post :create, {:comment_post => {}}, valid_session
        assigns(:comment_post).should be_a_new(CommentPost)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CommentPost.any_instance.stub(:save).and_return(false)
        post :create, {:comment_post => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested comment_post" do
        comment_post = CommentPost.create! valid_attributes
        # Assuming there are no other comment_posts in the database, this
        # specifies that the CommentPost created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CommentPost.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => comment_post.to_param, :comment_post => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested comment_post as @comment_post" do
        comment_post = CommentPost.create! valid_attributes
        put :update, {:id => comment_post.to_param, :comment_post => valid_attributes}, valid_session
        assigns(:comment_post).should eq(comment_post)
      end

      it "redirects to the comment_post" do
        comment_post = CommentPost.create! valid_attributes
        put :update, {:id => comment_post.to_param, :comment_post => valid_attributes}, valid_session
        response.should redirect_to(comment_post)
      end
    end

    describe "with invalid params" do
      it "assigns the comment_post as @comment_post" do
        comment_post = CommentPost.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CommentPost.any_instance.stub(:save).and_return(false)
        put :update, {:id => comment_post.to_param, :comment_post => {}}, valid_session
        assigns(:comment_post).should eq(comment_post)
      end

      it "re-renders the 'edit' template" do
        comment_post = CommentPost.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CommentPost.any_instance.stub(:save).and_return(false)
        put :update, {:id => comment_post.to_param, :comment_post => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested comment_post" do
      comment_post = CommentPost.create! valid_attributes
      expect {
        delete :destroy, {:id => comment_post.to_param}, valid_session
      }.to change(CommentPost, :count).by(-1)
    end

    it "redirects to the comment_posts list" do
      comment_post = CommentPost.create! valid_attributes
      delete :destroy, {:id => comment_post.to_param}, valid_session
      response.should redirect_to(comment_posts_url)
    end
  end

end
