require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NotificacionesAdminActualiceController do

  # This should return the minimal set of attributes required to create a valid
  # NotificacionesAdminActualouse. As you add validations to NotificacionesAdminActualouse, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NotificacionesAdminActualiceController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all notificaciones_admin_actualice as @notificaciones_admin_actualice" do
      notificaciones_admin_actualouse = NotificacionesAdminActualouse.create! valid_attributes
      get :index, {}, valid_session
      assigns(:notificaciones_admin_actualice).should eq([notificaciones_admin_actualouse])
    end
  end

  describe "GET show" do
    it "assigns the requested notificaciones_admin_actualouse as @notificaciones_admin_actualouse" do
      notificaciones_admin_actualouse = NotificacionesAdminActualouse.create! valid_attributes
      get :show, {:id => notificaciones_admin_actualouse.to_param}, valid_session
      assigns(:notificaciones_admin_actualouse).should eq(notificaciones_admin_actualouse)
    end
  end

  describe "GET new" do
    it "assigns a new notificaciones_admin_actualouse as @notificaciones_admin_actualouse" do
      get :new, {}, valid_session
      assigns(:notificaciones_admin_actualouse).should be_a_new(NotificacionesAdminActualouse)
    end
  end

  describe "GET edit" do
    it "assigns the requested notificaciones_admin_actualouse as @notificaciones_admin_actualouse" do
      notificaciones_admin_actualouse = NotificacionesAdminActualouse.create! valid_attributes
      get :edit, {:id => notificaciones_admin_actualouse.to_param}, valid_session
      assigns(:notificaciones_admin_actualouse).should eq(notificaciones_admin_actualouse)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new NotificacionesAdminActualouse" do
        expect {
          post :create, {:notificaciones_admin_actualouse => valid_attributes}, valid_session
        }.to change(NotificacionesAdminActualouse, :count).by(1)
      end

      it "assigns a newly created notificaciones_admin_actualouse as @notificaciones_admin_actualouse" do
        post :create, {:notificaciones_admin_actualouse => valid_attributes}, valid_session
        assigns(:notificaciones_admin_actualouse).should be_a(NotificacionesAdminActualouse)
        assigns(:notificaciones_admin_actualouse).should be_persisted
      end

      it "redirects to the created notificaciones_admin_actualouse" do
        post :create, {:notificaciones_admin_actualouse => valid_attributes}, valid_session
        response.should redirect_to(NotificacionesAdminActualouse.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved notificaciones_admin_actualouse as @notificaciones_admin_actualouse" do
        # Trigger the behavior that occurs when invalid params are submitted
        NotificacionesAdminActualouse.any_instance.stub(:save).and_return(false)
        post :create, {:notificaciones_admin_actualouse => {}}, valid_session
        assigns(:notificaciones_admin_actualouse).should be_a_new(NotificacionesAdminActualouse)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        NotificacionesAdminActualouse.any_instance.stub(:save).and_return(false)
        post :create, {:notificaciones_admin_actualouse => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested notificaciones_admin_actualouse" do
        notificaciones_admin_actualouse = NotificacionesAdminActualouse.create! valid_attributes
        # Assuming there are no other notificaciones_admin_actualice in the database, this
        # specifies that the NotificacionesAdminActualouse created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        NotificacionesAdminActualouse.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => notificaciones_admin_actualouse.to_param, :notificaciones_admin_actualouse => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested notificaciones_admin_actualouse as @notificaciones_admin_actualouse" do
        notificaciones_admin_actualouse = NotificacionesAdminActualouse.create! valid_attributes
        put :update, {:id => notificaciones_admin_actualouse.to_param, :notificaciones_admin_actualouse => valid_attributes}, valid_session
        assigns(:notificaciones_admin_actualouse).should eq(notificaciones_admin_actualouse)
      end

      it "redirects to the notificaciones_admin_actualouse" do
        notificaciones_admin_actualouse = NotificacionesAdminActualouse.create! valid_attributes
        put :update, {:id => notificaciones_admin_actualouse.to_param, :notificaciones_admin_actualouse => valid_attributes}, valid_session
        response.should redirect_to(notificaciones_admin_actualouse)
      end
    end

    describe "with invalid params" do
      it "assigns the notificaciones_admin_actualouse as @notificaciones_admin_actualouse" do
        notificaciones_admin_actualouse = NotificacionesAdminActualouse.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NotificacionesAdminActualouse.any_instance.stub(:save).and_return(false)
        put :update, {:id => notificaciones_admin_actualouse.to_param, :notificaciones_admin_actualouse => {}}, valid_session
        assigns(:notificaciones_admin_actualouse).should eq(notificaciones_admin_actualouse)
      end

      it "re-renders the 'edit' template" do
        notificaciones_admin_actualouse = NotificacionesAdminActualouse.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NotificacionesAdminActualouse.any_instance.stub(:save).and_return(false)
        put :update, {:id => notificaciones_admin_actualouse.to_param, :notificaciones_admin_actualouse => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested notificaciones_admin_actualouse" do
      notificaciones_admin_actualouse = NotificacionesAdminActualouse.create! valid_attributes
      expect {
        delete :destroy, {:id => notificaciones_admin_actualouse.to_param}, valid_session
      }.to change(NotificacionesAdminActualouse, :count).by(-1)
    end

    it "redirects to the notificaciones_admin_actualice list" do
      notificaciones_admin_actualouse = NotificacionesAdminActualouse.create! valid_attributes
      delete :destroy, {:id => notificaciones_admin_actualouse.to_param}, valid_session
      response.should redirect_to(notificaciones_admin_actualice_url)
    end
  end

end
