require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PublicCommentsController do

  # This should return the minimal set of attributes required to create a valid
  # PublicComment. As you add validations to PublicComment, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PublicCommentsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all public_comments as @public_comments" do
      public_comment = PublicComment.create! valid_attributes
      get :index, {}, valid_session
      assigns(:public_comments).should eq([public_comment])
    end
  end

  describe "GET show" do
    it "assigns the requested public_comment as @public_comment" do
      public_comment = PublicComment.create! valid_attributes
      get :show, {:id => public_comment.to_param}, valid_session
      assigns(:public_comment).should eq(public_comment)
    end
  end

  describe "GET new" do
    it "assigns a new public_comment as @public_comment" do
      get :new, {}, valid_session
      assigns(:public_comment).should be_a_new(PublicComment)
    end
  end

  describe "GET edit" do
    it "assigns the requested public_comment as @public_comment" do
      public_comment = PublicComment.create! valid_attributes
      get :edit, {:id => public_comment.to_param}, valid_session
      assigns(:public_comment).should eq(public_comment)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PublicComment" do
        expect {
          post :create, {:public_comment => valid_attributes}, valid_session
        }.to change(PublicComment, :count).by(1)
      end

      it "assigns a newly created public_comment as @public_comment" do
        post :create, {:public_comment => valid_attributes}, valid_session
        assigns(:public_comment).should be_a(PublicComment)
        assigns(:public_comment).should be_persisted
      end

      it "redirects to the created public_comment" do
        post :create, {:public_comment => valid_attributes}, valid_session
        response.should redirect_to(PublicComment.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved public_comment as @public_comment" do
        # Trigger the behavior that occurs when invalid params are submitted
        PublicComment.any_instance.stub(:save).and_return(false)
        post :create, {:public_comment => {}}, valid_session
        assigns(:public_comment).should be_a_new(PublicComment)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PublicComment.any_instance.stub(:save).and_return(false)
        post :create, {:public_comment => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested public_comment" do
        public_comment = PublicComment.create! valid_attributes
        # Assuming there are no other public_comments in the database, this
        # specifies that the PublicComment created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PublicComment.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => public_comment.to_param, :public_comment => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested public_comment as @public_comment" do
        public_comment = PublicComment.create! valid_attributes
        put :update, {:id => public_comment.to_param, :public_comment => valid_attributes}, valid_session
        assigns(:public_comment).should eq(public_comment)
      end

      it "redirects to the public_comment" do
        public_comment = PublicComment.create! valid_attributes
        put :update, {:id => public_comment.to_param, :public_comment => valid_attributes}, valid_session
        response.should redirect_to(public_comment)
      end
    end

    describe "with invalid params" do
      it "assigns the public_comment as @public_comment" do
        public_comment = PublicComment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PublicComment.any_instance.stub(:save).and_return(false)
        put :update, {:id => public_comment.to_param, :public_comment => {}}, valid_session
        assigns(:public_comment).should eq(public_comment)
      end

      it "re-renders the 'edit' template" do
        public_comment = PublicComment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PublicComment.any_instance.stub(:save).and_return(false)
        put :update, {:id => public_comment.to_param, :public_comment => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested public_comment" do
      public_comment = PublicComment.create! valid_attributes
      expect {
        delete :destroy, {:id => public_comment.to_param}, valid_session
      }.to change(PublicComment, :count).by(-1)
    end

    it "redirects to the public_comments list" do
      public_comment = PublicComment.create! valid_attributes
      delete :destroy, {:id => public_comment.to_param}, valid_session
      response.should redirect_to(public_comments_url)
    end
  end

end
